/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.punchcafe.implementations;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class HashMapTest {

    private HashMap<String, Integer> hashMap;

    @BeforeEach
    void beforeEach() {
        hashMap = new HashMap<String, Integer>();
    }

    @Test
    void canPutValueAndGetValue() {
        hashMap.put("One", 1);
        assertEquals(1, hashMap.get("One"));
    }
}
