/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef CPP_H
#define CPP_H

#ifdef _WIN32
#define CPP_EXPORT_FUNC __declspec(dllexport)
#else
#define CPP_EXPORT_FUNC
#endif

#include <string>

namespace cpp {
    class Greeter {
        public:
        std::string CPP_EXPORT_FUNC greeting();
    };
}

#endif
